/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './home/home.component.ngfactory';
import * as i4 from './about/about.component.ngfactory';
import * as i5 from './app.component.ngfactory';
import * as i6 from '@angular/common';
import * as i7 from '@angular/platform-browser';
import * as i8 from '@angular/animations/browser';
import * as i9 from '@angular/platform-browser/animations';
import * as i10 from '@angular/animations';
import * as i11 from '@angular/forms';
import * as i12 from '@angular/http';
import * as i13 from '@angular/router';
import * as i14 from './home/home.component';
import * as i15 from './about/about.component';
import * as i16 from './app-routing.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.HomeComponentNgFactory,i4.AboutComponentNgFactory,i5.AppComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i6.NgLocalization,i6.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,
          i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i7.DomSanitizer,i7.ɵe,
          [i6.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i7.DomSanitizer]),
          i0.ɵmpd(4608,i7.HAMMER_GESTURE_CONFIG,i7.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i7.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i7.ɵDomEventsPlugin(p0_0),new i7.ɵKeyEventsPlugin(p1_0),new i7.ɵHammerGesturesPlugin(p2_0,
                p2_1)];
          },[i6.DOCUMENT,i6.DOCUMENT,i6.DOCUMENT,i7.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i7.EventManager,i7.EventManager,[i7.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i7.ɵDomSharedStylesHost,i7.ɵDomSharedStylesHost,[i6.DOCUMENT]),
          i0.ɵmpd(4608,i7.ɵDomRendererFactory2,i7.ɵDomRendererFactory2,[i7.EventManager,
              i7.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i8.AnimationDriver,i9.ɵc,([] as any[])),
          i0.ɵmpd(5120,i8.ɵAnimationStyleNormalizer,i9.ɵd,([] as any[])),i0.ɵmpd(4608,
              i8.ɵAnimationEngine,i9.ɵb,[i8.AnimationDriver,i8.ɵAnimationStyleNormalizer]),
          i0.ɵmpd(5120,i0.RendererFactory2,i9.ɵe,[i7.ɵDomRendererFactory2,i8.ɵAnimationEngine,
              i0.NgZone]),i0.ɵmpd(6144,i7.ɵSharedStylesHost,(null as any),[i7.ɵDomSharedStylesHost]),
          i0.ɵmpd(4608,i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i7.Meta,
              i7.Meta,[i6.DOCUMENT]),i0.ɵmpd(4608,i7.Title,i7.Title,[i6.DOCUMENT]),
          i0.ɵmpd(4608,i10.AnimationBuilder,i9.ɵBrowserAnimationBuilder,[i0.RendererFactory2,
              i7.DOCUMENT]),i0.ɵmpd(4608,i11.ɵi,i11.ɵi,([] as any[])),i0.ɵmpd(4608,
              i12.BrowserXhr,i12.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i12.ResponseOptions,
              i12.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i12.XSRFStrategy,
              i12.ɵb,([] as any[])),i0.ɵmpd(4608,i12.XHRBackend,i12.XHRBackend,[i12.BrowserXhr,
              i12.ResponseOptions,i12.XSRFStrategy]),i0.ɵmpd(4608,i12.RequestOptions,
              i12.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i12.Http,i12.ɵc,[i12.XHRBackend,
              i12.RequestOptions]),i0.ɵmpd(5120,i13.ActivatedRoute,i13.ɵf,[i13.Router]),
          i0.ɵmpd(4608,i13.NoPreloading,i13.NoPreloading,([] as any[])),i0.ɵmpd(6144,
              i13.PreloadingStrategy,(null as any),[i13.NoPreloading]),i0.ɵmpd(135680,
              i13.RouterPreloader,i13.RouterPreloader,[i13.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i13.PreloadingStrategy]),i0.ɵmpd(4608,i13.PreloadAllModules,
              i13.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i13.ROUTER_INITIALIZER,
              i13.ɵi,[i13.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i13.ROUTER_INITIALIZER]),i0.ɵmpd(512,i6.CommonModule,i6.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i7.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i13.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i13.ɵg,i13.ɵg,[i0.Injector]),i0.ɵmpd(256,
              i0.APP_ID,'angular2-photo-gallery',([] as any[])),i0.ɵmpd(2048,i7.ɵTRANSITION_ID,
              (null as any),[i0.APP_ID]),i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,
              p0_1:any,p1_0:any,p2_0:any,p2_1:any,p2_2:any) => {
            return [i7.ɵc(p0_0,p0_1),i13.ɵh(p1_0),i7.ɵf(p2_0,p2_1,p2_2)];
          },[[2,i7.NgProbeToken],[2,i0.NgProbeToken],i13.ɵg,i7.ɵTRANSITION_ID,i6.DOCUMENT,
              i0.Injector]),i0.ɵmpd(512,i0.ApplicationInitStatus,i0.ApplicationInitStatus,
              [[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,i0.ɵe,[i0.NgZone,i0.ɵConsole,
              i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,i0.ApplicationInitStatus]),
          i0.ɵmpd(2048,i0.ApplicationRef,(null as any),[i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,
              i0.ApplicationModule,[i0.ApplicationRef]),i0.ɵmpd(512,i7.BrowserModule,
              i7.BrowserModule,[[3,i7.BrowserModule]]),i0.ɵmpd(512,i9.BrowserAnimationsModule,
              i9.BrowserAnimationsModule,([] as any[])),i0.ɵmpd(512,i11.ɵba,i11.ɵba,
              ([] as any[])),i0.ɵmpd(512,i11.FormsModule,i11.FormsModule,([] as any[])),
          i0.ɵmpd(512,i12.HttpModule,i12.HttpModule,([] as any[])),i0.ɵmpd(1024,i13.ɵa,
              i13.ɵd,[[3,i13.Router]]),i0.ɵmpd(512,i13.UrlSerializer,i13.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i13.ChildrenOutletContexts,i13.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i13.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i6.LocationStrategy,i13.ɵc,[i6.PlatformLocation,[2,i6.APP_BASE_HREF],
              i13.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i6.Location,i6.Location,[i6.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i13.ROUTES,() => {
            return [[{path:'',component:i14.HomeComponent},{path:'about',component:i15.AboutComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i13.Router,i13.ɵe,[i0.ApplicationRef,i13.UrlSerializer,
              i13.ChildrenOutletContexts,i6.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i13.ROUTES,i13.ROUTER_CONFIGURATION,[2,i13.UrlHandlingStrategy],
              [2,i13.RouteReuseStrategy]]),i0.ɵmpd(512,i13.RouterModule,i13.RouterModule,
              [[2,i13.ɵa],[2,i13.Router]]),i0.ɵmpd(512,i16.AppRoutingModule,i16.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2p1bGlldHRldHdvcnNleS9EZXNrdG9wL2FuZ3VsYXItZ2FsbGVyeS1oZXJva3Uvc3JjL2FwcC9hcHAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2p1bGlldHRldHdvcnNleS9EZXNrdG9wL2FuZ3VsYXItZ2FsbGVyeS1oZXJva3Uvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
