/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './home.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../gallery/gallery.component.ngfactory';
import * as i3 from '../gallery/gallery.component';
import * as i4 from './home.component';
import * as i5 from '@angular/platform-browser';
const styles_HomeComponent:any[] = [i0.styles];
export const RenderType_HomeComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_HomeComponent,data:{'animation':[{type:7,name:'explainerAnim',definitions:[{type:1,
        expr:'* => *',animation:[{type:11,selector:'.col',animation:{type:6,styles:{opacity:0,
            transform:'translateX(-40px)'},offset:(null as any)},options:(null as any)},
            {type:11,selector:'.col',animation:{type:12,timings:'500ms',animation:[{type:4,
                styles:{type:6,styles:{opacity:1,transform:'translateX(0)'},offset:(null as any)},
                timings:'800ms 1.2s ease-out'}]},options:(null as any)},{type:11,selector:'.col',
                animation:[{type:4,styles:{type:6,styles:'*',offset:(null as any)},
                    timings:1000}],options:(null as any)}],options:(null as any)}],
        options:{}}]}});
export function View_HomeComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n\n\n'])),(_l()(),i1.ɵeld(1,
      0,(null as any),(null as any),7,'div',([] as any[]),[[24,'@explainerAnim',0]],
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,
      (null as any),['\n   '])),(_l()(),i1.ɵeld(3,0,(null as any),(null as any),4,
      'div',[['class','col']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted(-1,(null as any),['\n     '])),(_l()(),i1.ɵeld(5,
      0,(null as any),(null as any),1,'gallery',([] as any[]),(null as any),(null as any),
      (null as any),i2.View_GalleryComponent_0,i2.RenderType_GalleryComponent)),i1.ɵdid(6,
      49152,(null as any),0,i3.GalleryComponent,([] as any[]),{datasource:[0,'datasource']},
      (null as any)),(_l()(),i1.ɵted(-1,(null as any),['\n   '])),(_l()(),i1.ɵted(-1,
      (null as any),['\n'])),(_l()(),i1.ɵted(-1,(null as any),['\n\n\n'])),(_l()(),
      i1.ɵted(-1,(null as any),['\n']))],(_ck,_v) => {
    var _co:i4.HomeComponent = _v.component;
    const currVal_1:any = _co.images;
    _ck(_v,6,0,currVal_1);
  },(_ck,_v) => {
    const currVal_0:any = (undefined as any);
    _ck(_v,1,0,currVal_0);
  });
}
export function View_HomeComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-home',([] as any[]),
      (null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent)),
      i1.ɵdid(1,114688,(null as any),0,i4.HomeComponent,[i5.Meta,i5.Title],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const HomeComponentNgFactory:i1.ComponentFactory<i4.HomeComponent> = i1.ɵccf('app-home',
    i4.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2p1bGlldHRldHdvcnNleS9EZXNrdG9wL2FuZ3VsYXItZ2FsbGVyeS1oZXJva3Uvc3JjL2FwcC9ob21lL2hvbWUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2p1bGlldHRldHdvcnNleS9EZXNrdG9wL2FuZ3VsYXItZ2FsbGVyeS1oZXJva3Uvc3JjL2FwcC9ob21lL2hvbWUuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvanVsaWV0dGV0d29yc2V5L0Rlc2t0b3AvYW5ndWxhci1nYWxsZXJ5LWhlcm9rdS9zcmMvYXBwL2hvbWUvaG9tZS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2p1bGlldHRldHdvcnNleS9EZXNrdG9wL2FuZ3VsYXItZ2FsbGVyeS1oZXJva3Uvc3JjL2FwcC9ob21lL2hvbWUuY29tcG9uZW50LnRzLkhvbWVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcblxuXG48ZGl2IEBleHBsYWluZXJBbmltPlxuICAgPGRpdiBjbGFzcz1cImNvbFwiPlxuICAgICA8Z2FsbGVyeSAgW2RhdGFzb3VyY2VdPWltYWdlcz48L2dhbGxlcnk+XG4gICA8L2Rpdj5cbjwvZGl2PlxuXG5cbjwhLS0gPGRpdj5cbiAgPGRpdiBpZD1cImZsZXhIMVwiPjxtb2hhdmU+PC9tb2hhdmU+PC9kaXY+XG48L2Rpdj4gLS0+XG4iLCI8YXBwLWhvbWU+PC9hcHAtaG9tZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQSw4Q0FHQTtNQUFBO01BQUEsMERBQW9CO01BQUEsMEJBQ2pCO01BQUE7TUFBQSxnQkFBaUIsK0NBQ2Y7TUFBQTtNQUFBLGlGQUFBO01BQUE7TUFBQSxlQUF3Qyw2Q0FDcEM7TUFBQSx1QkFDSCw4Q0FLSTthQUFBOztJQVBLO0lBQVYsV0FBVSxTQUFWOztJQUZBO0lBQUwsV0FBSyxTQUFMOzs7O29CQ0hBO01BQUE7YUFBQTtVQUFBO0lBQUE7Ozs7In0=
